### ISSUE TITLE
Discutir Integrar analytics

### ISSUE THREAD

**Issue by holomorfo** [sptm-unam/seminario-app#105]
Puede ser Google analytics pero ese es privado.

Otras opciones podrían ser como estás
[Analytics](https://www.tinybird.co/blog-posts/google-analytics-alternative-in-3-minutes?psafe_param=1&utm_source=Google+Paid&utm_medium=cpc&utm_campaign=Search+DSA+Blog&utm_content=143603275573&utm_term=&utm_term=&utm_campaign=SEARCH+-+Blog+Articles&utm_source=adwords&utm_medium=ppc&hsa_acc=9980863893&hsa_cam=19009410883&hsa_grp=143603275573&hsa_ad=636747861799&hsa_src=g&hsa_tgt=dsa-1907811445103&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gclid=CjwKCAjw0N6hBhAUEiwAXab-TRwQuKixMxBm9x2YHYZ_V4eMHpHFQ1biCsHep3qMx-DMPAtSEDWvNRoCKxwQAvD_BwE)

**Comment by holomorfo** [comment]
Que opinan acerca de integrar algun tipo de analytics?
@hvillase @EmilioOcelotl @mezaga @MarianneTeixido @Elliot-Hernandez

**Comment by Elliot-Hernandez** [comment]
Por mi está super bien en implementarlo, cualquiera de las dos opciones me parecen bastante bien.

**Comment by holomorfo** [comment]
- Es realmente necesario?
- Que beneficios trae?
- Puede ser util para ver que traducciones serian mas necesarias.
- Que tan comun es su uso en la academia y en la industria.
- Es un buen ejercicio didactico.
- Puede servir como reporte de impacto.
