### ISSUE TITLE
Agregar opcion para correr live coding en version Movil

### ISSUE THREAD

**Issue by holomorfo** [sptm-unam/seminario-app#156]
Deberiamos tener un boton para simular el ctrl+enter para los usuarios que se conecten por un dispositivo movil.
Como te parece que seria buena idea @Elliot-Hernandez ?

**Comment by Elliot-Hernandez** [comment]
Si, me parece bastante bien poner algo así para los usuarios de celular.

**Comment by holomorfo** [comment]
Si, quizá un botón play que esté sobre el editor o arribista, podrías ir eligiendo un estilo y poner un botón de placeholder mientras por favor?

**Comment by holomorfo** [comment]
https://github.com/sptm-unam/seminario-app/pull/177

**Comment by holomorfo** [comment]
https://github.com/sptm-unam/seminario-app/pull/179
