### ISSUE TITLE
Elegir Licencia (Encuesta e implementacion)

### ISSUE THREAD

**Issue by holomorfo** [sptm-unam/seminario-app#167]

**Comment by ninioArtillero** [comment]
En la siguiente liga podemos ver una descripción breve y concisa sobre las opciones más usuales de licencia de código abierto: https://www.codecademy.com/article/choosing-an-open-source-license

Creo que podemos acotar la cuestión a decidir entre GPL 3 y MIT, las dos más populares en GitHub. 

GPL 3 cualquier proyecto que utilice el código a tener la misma licencia (garantizando la apertura de los derivados).

MIT, es una licencia permisiva que para términos prácticos sólo exije que no se declare autoría sobre el código (procurando acompañar el mismo con una copia de la licencia).

Creo que por la naturaleza académica y educativa de la "seminario app", esta debería ser puesta en licencia GPL v3.

La desición no tiene por que ser definitiva. De ser necesario podemos replantear adoptar otra licencia o, por ejemplo, independizar la librería y asignarle una licencia diferente si quisieramos.

**Comment by ninioArtillero** [comment]
Otras fuentes:

https://www.gnu.org/licenses/license-recommendations.es.html

https://barcelonageeks.com/como-elegir-la-licencia-de-codigo-abierto-adecuada/

**Comment by ninioArtillero** [comment]
El tema de la licencia de código es sútil y se puede extender más allá de la cuenta. El martes compartiré una encuesta vía telegram para elegir una licencia. Si no hay mayoría absoluta para alguna licencia, haremos una segunda ronda de encuesta con las 2 que hubieran recibido más votos.

De momento considero incluir en la encuesta las siguientes licencias:

[GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html) - Copyleft
[LPGL v3](https://www.gnu.org/licenses/lgpl-3.0.html) - Copyleft permisiva
[MIT License](https://mit-license.org/) - Permisiva
[Apache License](https://apache.org/licenses/LICENSE-2.0) - Permisiva
ISC License

Si alguien considera incluir otra en la encuesta por favor comentelo. Gracias :)
Otra referencias:

https://choosealicense.com/community/
https://blog.zenhub.com/the-5-best-open-source-licenses-for-securing-your-software-rights/
https://dev.to/krtirtho/choosing-open-source-license-wisely-1m3p

**Comment by holomorfo** [comment]
Este post se ve interesante tambien:
https://www.quora.com/Can-you-explain-the-difference-between-MIT-GPL-and-LGPL-licenses
- The MIT License (free) is a permissive free software license originating at the Massachusetts Institute of Technology (MIT) in the late 1980s. As a permissive license, it puts only very limited restriction on reuse and has, therefore, high license compatibility.
- The GNU General Public License (free) (GNU GPL or simply GPL) is a series of widely used free software licenses that guarantee end users the four freedoms to run, study, share, and modify the software BUT is otherwise restrictive which is why its only popular for Linux
- The GNU Lesser General Public License (LGPL) (free) is a free-software license published by the Free Software Foundation (FSF). The license allows developers and companies to use and integrate a software component released under the LGPL into their own (even proprietary) software without being required by the terms of a strong copyleft license to release the source code of their own components. However, any developer who modifies an LGPL-covered component is required to make their modified version available under the same LGPL license. This is an attempt to make the GPL type license a little bit more palatable but is still inferior to the MIT and BSD licenses

**Comment by holomorfo** [comment]
Encuenta realizada, sin conclusion pero hubo avance, se elegira mas adelante
