### ISSUE TITLE
Mal mapeo de las notas, si natural suena siempre como si bemol

### ISSUE THREAD

**Issue by slendro64** [sptm-unam/seminario-app#199]
Todos los SI natural suenan en cambio como si bemol. Supongo que está relacionado con la falta de bemoles y sostenidos.

**Comment by holomorfo** [comment]
Muchas gracias por la observacion, ya quedo corregido en el commit 
https://github.com/sptm-unam/seminario-app/commit/10f1c00a78b1eb03a08e5519832307ff5f8a2f4e
