### ISSUE TITLE
Sostenidos y bemoles no claros

### ISSUE THREAD

**Issue by Lu-YangMusic** [sptm-unam/seminario-app#206]
Cuando se escriben notas como c d e...etc al escribir b correspondiente a la nota si, se escucha por defecto si bemol. ¿cómo se puede lograr que los sonidos sean sostenidos o bemoles?

**Comment by holomorfo** [comment]
Habia un error con la nota "b" ya quedo corregido
Muchas gracias por la observacion, ya quedo corregido en el commit 
https://github.com/sptm-unam/seminario-app/commit/10f1c00a78b1eb03a08e5519832307ff5f8a2f4e

Aun no se pueden correr sostenidos y bemoles, estamos trabajando en ello.
