### ISSUE TITLE
Flujo de señal de la app

### ISSUE THREAD

**Issue by hvillase** [sptm-unam/seminario-app#46]
Dibujar una gráfica con el flujo de señal de la app.
- ¿qué programa colaborativo podemos usar?

**Comment by hvillase** [comment]
Hola Cristian. Sí abre el diagrama. Me refiero a un diagrama que nos permita visualizar las conexiones del proyecto. De repente me pierdo que está conectado con qué, y eso me dificulta ver hacia que objetivos vamos. Puede funcionar un tipo de diagrama como el que muestras.

**Comment by ninioArtillero** [comment]
Gracias por compartir esas referencias Cristián, y a ti Hernani por sugerir esta representación del proyecto. Hasta donde entiendo, la idea de "flujo de señal de la app", nos daría por ejemplo:

* Una idea de cómo se acomodan en el proyecto las librerías clave (como codemirror).
* Y cómo se conectan (topológicamente) las partes del código que hemos escrito, probablemente desembocando al index.html (¿?). Es decir, nos daría una vista panorámica de la modularización interna de la aplicación.

Voy a meterle mano a esto, y les pediré su apoyo para refinarlo.

Disculpen que a penas respondo: le estoy agarrando al sistema de notificaciones de GitHub =/

**Comment by ninioArtillero** [comment]
@hvillase , ¿lo que pensaste es algo similar a esto? 

![seminario-app drawio](https://user-images.githubusercontent.com/64996634/229653856-ed5876f0-f5de-43f6-9c9e-2e65acb2a676.png)

Este diagrama expresa, a mi entender y a _grosso modo_, la forma en que está estructurado el código de la app hasta el momento.  Necesita corregirse, extenderse y refinarse.

@holomorfo Estoy haciendo pruebas a ver que tan complicado es añadir un diagrama de gojs. Con esta herramienta se podría tener un diagrama interactivo como parte de la app.

**Comment by EmilioOcelotl** [comment]
Está muy cool esto de gojs. He estado revisando algo de la documentación y el siguiente enlace sugiere que podríamos guardar todo en un archivo json: 

[flowchart](https://gojs.net/latest/samples/flowchart.html)

También podríamos reutilizar el código (view the code) que ya está escrito ahí y hacer algunas modificaciones. 

Pienso que un paso siguiente podría implicar a la librería de sonido: me imagino que podríamos asociar la conexión y la creación de objetos en gojs con la creación y conexión de nodos de webaudioapi. De esta manera veríamos de manera gráfica cómo están conectadas las cosas en sonido.js y al mismo tiempo, escucharlas.

**Comment by ninioArtillero** [comment]
Justo estaba checando ese ejemplo. Me parece genial la idea que propones.

**Comment by holomorfo** [comment]
Este tambien se ve muy bien. Podemos simplemente organizar todo en un JSON y obtener una grafica como esta:
https://jsoncrack.com/editor


![Image](https://user-images.githubusercontent.com/9595617/231063155-7854f109-eedc-4b1e-ba41-dc9ff06cc24f.png)

**Comment by ninioArtillero** [comment]
Elaborare el JSON sugerido por @holomorfo, para tener una representación del código hasta la fecha. He pensado en descartar la opción de GoJs por ser muy complicado y no central, además de que se trata de software privativo: Véase sección 2.1.1 (a) en https://github.com/NorthwoodsSoftware/GoJS/blob/master/license.html

**Comment by ninioArtillero** [comment]
De momento tengo esta propuesta en generada con JSON

![Image](https://user-images.githubusercontent.com/64996634/231883866-004b9a59-2ee4-4db0-ba7c-6e13b7bb285a.png)

Puedo subir el archivo diagrama.json a la raíz del repositoriom ¿qué opinan?

**Comment by holomorfo** [comment]
Me parece bien que lo agregues al repositorio, gracias

**Comment by ninioArtillero** [comment]
Es un diagrama que muestra la estructura del código contenido en el repositorio. No es un flujo de señal tal cual: no sé como producir una topología que no sea de árbol y haga más claro el flujo de señal sin necesidad de nodos tipo "go to".
