### ISSUE TITLE
Elegir framework para frontend (UI)

### ISSUE THREAD

**Issue by ninioArtillero** [sptm-unam/seminario-app#47]
Como vimos en la sesión del 16 de marzo ([ver docs](https://github.com/sptm-unam/sptm-docs)) existe un extenso ecosistema de frameworks para desarrollo web.
Se trata de librerías que permiten en general (corríjanme si me equivoco) manipular HTML y JavaScript como una unidad. 

Debemos decidir sí queremos usar un framework para nuestro proyecto. @holomorfo presento [React](https://react.dev/), [Vue](https://vuejs.org/), [JQuery]() y [Angular](https://angular.io/) como referentes.

Adicionalmente propongo echar un ojo a algunas alternativas interesantes como [Alpine](https://alpinejs.dev/) y [Qwik](https://qwik.builder.io/)

Este [video de Fireship](https://youtu.be/SJeBRW1QQMA) es una buena referencia para entender este _problema_.

**Comment by hvillase** [comment]
Habíamos platicado de usar Bootstrap. Veo que en la sección <head> estamos apuntando a Boostrap y a JQuery, quizá si escogemos el framework de Bootstrap 5 (que cambió el trabajo de jQuery por JS) podemos ahorrarnos una capa de tecnología. Acá el tutorial de BS 5 de w3schools menciona cómo implementar Bootstrap 5 (https://www.w3schools.com/bootstrap5/index.php).

**Comment by holomorfo** [comment]
Para la primera version solo requerimos un poco de jquery, retomaremos esta discusion para otras versiones
