### ISSUE TITLE
Probar GIthub pages para CICD

### ISSUE THREAD

**Issue by hvillase** [sptm-unam/seminario-app#49]
Para crear una GitHub page hay que ir al index.html y asignar un segumiento. En settings > pages se declara esta conversión a página web. Ahí sale una url compuesta por el usuario.io/nombre del repositorio.

**Comment by holomorfo** [comment]
Este enlace es util para manejar los ambientes de produccion

https://medium.com/geekculture/when-youre-working-on-a-static-site-and-github-pages-feels-like-the-perfect-hosting-solution-a41c37f4e326

**Comment by holomorfo** [comment]
Para usar github pages con CICD necesitamos tener el index en el root directory o en una carpeta llamada docs, de momento lo tenemos en root y si necesitamos algo mas complicado podemos usar github actions.
