### ISSUE TITLE
Integrar https://codemirror.net/ a una pagina

### ISSUE THREAD

**Issue by holomorfo** [sptm-unam/seminario-app#50]
- Crear una pagina de ejemplo que integre code mirror y ejecute alguna linea de codigo
- revisar si se puede acceder al WebAudioAPI desde estos bloques de codigo

**Comment by ninioArtillero** [comment]
Me parece apropiado apegarnos a la convención, siempre que salirse de ella no tenga mejores prospectos. 

En nuestro caso, que no empezamos index.js, propongo que sigamos con sonido.js
Cómo dice el dicho, "si no se ha roto, no lo arregles" :P

Por cierto, supongo que este issue queda cerrado con el pull request #67
