### ISSUE TITLE
documentación, wiki y artículo

### ISSUE THREAD

**Issue by EmilioOcelotl** [sptm-unam/seminario-app#57]
Me quedé pensando si estaría bueno dejar una especie de tutorial en la wiki del github o en algún otro  lugar del repositorio. Esto podría ser significativo para otros momentos del seminario e incluso para personas externas al posgrado. 
Pienso que cuando lleguemos al diseño de una especie de interfaz de texto, que puede ser un lenguaje o solamente funciones ajustadas a las necesidades de la librería, la información de ese "tutorial" más las reflexiones del diseño de la interfaz  y las conclusiones pertinentes podrían prácticamente ser un artículo académico que podría publicarse y presentarse en algún lado.

**Comment by holomorfo** [comment]
https://github.com/sptm-unam/sptm-docs/pull/11
