### ISSUE TITLE
Problema relacionado con rutas de html y js 

### ISSUE THREAD

**Issue by EmilioOcelotl** [sptm-unam/seminario-app#66]
Parece ser que la última actualización de index.html toma como referencia algunos eventos que suceden en el documento como botones pero que no están relacionados con las rutas que tiene sonido.js. De hecho la referencia a sonido.js en index.html aparece en otra carpeta. 

Por otro lado, estuve haciendo pruebas directamente en sonido.html y en se momento no consideré que los archivos de instalación de npm podían estar a la misma altura que index.html. 

Entonces me quedo pensando en estas soluciones, no sé qué piensen: 

1. No me quedó claro si el contenido de la página aparecerá continuo o separado por html independientes ( index.html sugiere que sí). 
2. En caso de que sea así, pienso los problemas anteriores se podrían resolver subiendo los archivos de html una carpeta arriba (npm, estáticos, sonido.js y js) para que estén al mismo nivel que index.html 
3. Si vamos por esta opción, los archivos dentro de html creo que son innecesarios.

**Comment by holomorfo** [comment]
Estas haciendo un build con Parcel? O estás corriendo el index.html directamente desde la carpeta root?

**Comment by EmilioOcelotl** [comment]
Había estado usando parcel dentro de html para seguir haciendo pruebas en sonido.js pero por alguna extraña razón no me deja hacer build 

![Captura desde 2023-03-27 18-16-27](https://user-images.githubusercontent.com/8987515/228094919-4bc23d5f-0d08-4e14-ad3b-7c9a9e7a4708.png)

Y cuando la cambio arroja más errores por ejemplo cambiar a module por los imports, con lo último solucionado, arroja:

![Captura desde 2023-03-27 18-19-02](https://user-images.githubusercontent.com/8987515/228095294-43b06d36-a6a9-4869-b530-70a122b6cb25.png)

**Comment by holomorfo** [comment]
Gracias, parece que le falta un parámetro de configuración a Parcel, deja lo reviso

**Comment by holomorfo** [comment]
@EmilioOcelotl ya tengo una solucion de propuesta, la palticamos en la sesion.
