### ISSUE TITLE
Actualizar estilo de los botones

### ISSUE THREAD

**Issue by holomorfo** [sptm-unam/seminario-app#86]
Estaba pensando en implementar un estilo para los botones, algo como esto:
https://copy-paste-css.com/
https://cantina.co/building-a-better-button-in-css/
https://www.freecodecamp.org/news/css-button-style-hover-color-and-background/

En caso de que no queramos usar un framework. Que te parece, puedes tomar esta tarea?

**Comment by Elliot-Hernandez** [comment]
Hola, perdón por la tardanza.
Si, yo me encargo
